name: mj_image_slider
description: A Flutter package for all platforms which provides a simple image slider with/without animation
version: 0.0.1
homepage: https://github.com/miladjalalli/MJ-Image-Slider

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: